eureka:
  client:
    service-url:
      defaultZone: http://feint:feint123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 8687

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/feintkotlin
    username: root
    password:
  mail:
    host: smtp.qq.com
    username: feintkotlin@qq.com
    password: ryowejzdvputgghc
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  application:
    name: email-manager
