eureka:
  client:
    service-url:
      defaultZone: http://feint:feint123@${feintkotlin.host}:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    ip-address: ${feintkotlin.ip}

server:
  port: 8689

spring:
  application:
    name: file-manager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/feintkotlin?characterEncoding=utf8
    username: root
    password: ${feintkotlin.database.password}

#feintkotlin:
#  host: 39.108.124.125
#  database:
#    password: feint123
#  ip: 120.77.34.140

feintkotlin:
  host: localhost
  database:
    password:
  ip: 127.0.0.1